### ISSUE TITLE
npm run start  Error: Child compilation failed:

### ISSUE THREAD

**Issue by alkuma** [hannahcode/wordle#46]
Firstly, great work on this wordle clone!

Following the instructions at https://github.com/hannahcode/wordle#wordle-clone I got this error
```
$ npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 1403 packages in 3.678s

166 packages are looking for funding
  run `npm fund` for details

found 9 vulnerabilities (2 low, 6 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```
So far so good!

```
$ npm run start
...
TypeError: (intermediate value)(intermediate value)(intermediate value).slice(...).reverse(...).flatMap is not a function
assets by path static/js/*.js 2.18 MiB
  asset static/js/bundle.js 2.17 MiB [emitted] (name: main) 1 related asset
  asset static/js/node_modules_web-vitals_dist_web-vitals_js.chunk.js 6.88 KiB [emitted] 1 related asset
asset index.html 561 bytes [emitted]
asset asset-manifest.json 458 bytes [emitted]
cached modules 1.87 MiB (javascript) 31.3 KiB (runtime) [cached] 413 modules
./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/index.css 39 bytes [built] [1 error]

ERROR in ./src/index.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/index.css)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: (intermediate value)(intermediate value)(intermediate value).slice(...).reverse(...).flatMap is not a function
    at Object.getAllConfigs [as default] (/home/alok/github/wordle/node_modules/tailwindcss/lib/util/getAllConfigs.js:17:26)
    at Object.resolveConfig [as default] (/home/alok/github/wordle/node_modules/tailwindcss/lib/public/resolve-config.js:14:60)
    at getTailwindConfig (/home/alok/github/wordle/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:65:52)
    at /home/alok/github/wordle/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:124:92
    at /home/alok/github/wordle/node_modules/tailwindcss/lib/processTailwindFeatures.js:39:11
    at plugins (/home/alok/github/wordle/node_modules/tailwindcss/lib/index.js:20:104)
    at LazyResult.runOnRoot (/home/alok/github/wordle/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/home/alok/github/wordle/node_modules/postcss/lib/lazy-result.js:393:26)
    at LazyResult.async (/home/alok/github/wordle/node_modules/postcss/lib/lazy-result.js:221:30)
    at LazyResult.then (/home/alok/github/wordle/node_modules/postcss/lib/lazy-result.js:206:17)
 @ ./src/index.css 8:6-262 22:17-24 26:7-21 58:25-39 59:36-47 59:50-64 63:6-73:7 64:54-65 64:68-82 70:42-53 70:56-70 72:21-28 83:0-232 83:0-232 84:22-29 84:33-47 84:50-64 61:4-74:5
 @ ./src/index.tsx 6:0-21

ERROR in Module.createRequire is not a function

ERROR in   Error: Child compilation failed:
  Module.createRequire is not a function
  
  - child-compiler.js:169 childCompiler.runAsChild
    [wordle]/[html-webpack-plugin]/lib/child-compiler.js:169:18
  
  - Compiler.js:559 compile
    [wordle]/[webpack]/lib/Compiler.js:559:11
  
  - Compiler.js:1129 hooks.afterCompile.callAsync.err
    [wordle]/[webpack]/lib/Compiler.js:1129:17
  
  
  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7
  


1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack 5.65.0 compiled with 4 errors in 1072 ms
Files successfully emitted, waiting for typecheck results...
Issues checking in progress...
No issues found.
```

and http://localhost:3000 throws up
![2022-01-23 11-50-46 से स्क्रीनशॉट](https://user-images.githubusercontent.com/3204475/150667440-d267644b-b21e-4431-8491-05a05fe1e2e1.png)

```
Html Webpack Plugin:
  Error: Child compilation failed:
  Module.createRequire is not a function
  
  - child-compiler.js:169 childCompiler.runAsChild
    [wordle]/[html-webpack-plugin]/lib/child-compiler.js:169:18
  
  - Compiler.js:559 compile
    [wordle]/[webpack]/lib/Compiler.js:559:11
  
  - Compiler.js:1129 hooks.afterCompile.callAsync.err
    [wordle]/[webpack]/lib/Compiler.js:1129:17
  
  
  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7
```

I'm trying to solve this, but just posting here in case someone already encountered it and knows of a solution.

**Comment by alkuma** [comment]
```$ which node
/usr/bin/node
[alok@alok wordle](main)$ node -v
v10.24.0
[alok@alok wordle](main)$ npm -v
6.14.11
```

This was because I had an old version of npm.

To switch to the new version I did the following

```
sudo yum module reset nodejs
```
Followed by
```
sudo yum module enable nodejs:16
```
and finally
```
sudo yum install nodejs
```

Leading to 

```
$ node -v
v16.13.1
[alok@alok ~]$ npm -v
8.1.2
```

Thanks to the instructions at https://docs.centos.org/en-US/8-docs/managing-userspace-components/assembly_managing-versions-of-appstream-content/

wordle comes up now! Posting here in case anybody else faces this issue, and closing the issue.
